### ISSUE TITLE
Result::unwrap() - Content: duplicate entry with key m_Name (from LowPolyUltimatePack.unitypackage)

### ISSUE THREAD

**Issue by alfredbaudisch** [barcoderdev/unitypackage_godot#14]
When trying to extract https://assetstore.unity.com/packages/3d/props/low-poly-ultimate-pack-54733 in Windows 10: `.\unitypackage_util.exe LowPolyUltimatePack.unitypackage dump`

Got: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an
`Err` value: Error("content: duplicate entry with key \"m_Name\"", line: 23157, column: 3)', src\commands.rs:46:58
```

Any way that I can help debugging further?

**Comment by barcoderdev** [comment]
The way I debug these is to run unitypackage_util from source, with `cargo run -- "/Volumes/Samsung X5/UnityPackages/Low Poly Ultimate Pack.unitypackage" dump` with some println's uncommented.

See https://github.com/barcoderdev/unitypackage_util/blob/a7af585ebd4d2512a1925cc9bb8fb2665f2b7fae/src/commands.rs#L76

```
println!("guid: {:?}", guid);

println!("checking pathname");

println!("checking asset.meta");

println!("checking asset");
```

This shows me what file it was working on when it crashed.  From there I extract the package to disk and examine the yaml manually, usually the `{guid}/asset` file.

For this package I'm getting:

```
...
guid: "6b53164a4c6c8744680ea57a798e6aa1"
guid: "6b5559adca910d540a4fe673a1727602"
guid: "6b5559adca910d540a4fe673a1727602"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("content: duplicate entry with key \"m_Name\"", line: 23157, column: 3)', src/commands.rs:46:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`6b5559adca910d540a4fe673a1727602/pathname` shows the file with the issue is `Assets/polyperfect/Low Poly Ultimate Pack/06 - Castle.unity`

Searching `6b5559adca910d540a4fe673a1727602/asset` (a yaml file) for `m_Name:` finds this:

```
--- !u!114 &1709481619
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 1709481618}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 1897577771}
  m_Name: 
  m_EditorClassIdentifier: 
  m_Name: 
  m_Name: 
  m_Name: 
  m_Name: 
--- !u!114 &1709481620
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 1709481618}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 1897577771}
  m_Name: 
  m_EditorClassIdentifier: 
  m_Name: 
  m_Name: 
  m_Name: 
  m_Name: 
```

These are the source of `duplicate entry with key \"m_Name\""`

From here I'd research if serde has a way to handle duplicate keys, which could be a bit tricky to implement.  Or I'd be lazy and regex it out somehow in the `asset_yaml_cleanup` function in lib.rs.
